name: yofardev_ai
description: "Animated AI avatar"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.3
  just_audio: ^0.9.38
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  audio_analyzer:
    path: /Users/yofardev/development/Projects/Flutter/PLUGINS/audio_analyzer
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  nested: ^1.0.0
  flutter_parsed_text: ^2.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  image_picker: ^1.1.2
  path: ^1.9.0
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  flutter_volume_controller: ^1.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint:
  flutter_native_splash: ^2.4.1


flutter_native_splash:
  color: "#438EFF"
  image: "assets/splash.png"
  android_12:
    color: "#438EFF"
    icon_background_color: "#438EFF"
    image: "assets/splash.png"

 

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/sound_effects/
    - assets/lotties/
    - assets/avatar/
    - assets/avatar/mouth/
    - assets/avatar/accessories/
    - assets/avatar/backgrounds/
    - assets/avatar/costumes/
    - assets/avatar/top/
    - assets/avatar/bottom/

