name: yofardev_ai
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  google_generative_ai: ^0.4.3
  just_audio: ^0.9.38
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  audio_analyzer:
    path: /Users/yofardev/development/Projects/Flutter/PLUGINS/audio_analyzer
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  nested: ^1.0.0
  flutter_parsed_text: ^2.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  image_picker: ^1.1.2
  path: ^1.9.0
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#436fff"
  image: "assets/logo.jpeg"
  android_12:
    color: "#436fff"
    icon_background_color: "#436fff"

 

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sound_effects/
    - assets/base/
    - assets/lotties/
