name: yofardev_ai
description: "Animated AI avatar"

publish_to: "none"

version: 3.0.0+6

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supertonic_flutter: ^0.1.3
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  audio_analyzer: ^0.1.0
  flutter_bloc: ^9.1.1
  nested: ^1.0.0
  flutter_parsed_text: ^2.2.1
  intl: ^0.20.2
  lottie: ^3.3.2
  image_picker: ^1.2.1
  path: ^1.9.1
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  flutter_volume_controller: ^1.3.4
  http: ^1.6.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  uuid: ^4.5.2
  math_expressions: ^3.1.0
  alarm: ^5.1.5
  shimmer: ^3.0.0
  html: ^0.15.6
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  flutter_inappwebview: ^6.1.5
  get_it: ^9.2.1
  freezed_annotation: ^3.1.0
  freezed: ^3.2.5
  json_annotation: ^4.11.0
  google_fonts: ^8.0.2
  fpdart: ^1.2.0
  go_router: ^17.1.0

  dartz: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.11.1
  json_serializable: ^6.13.0
  flutter_lints:
  flutter_native_splash: ^2.4.1


  mocktail: any
flutter_native_splash:
  color: "#438EFF"
  image: "assets/splash.png"
  android_12:
    color: "#438EFF"
    icon_background_color: "#438EFF"
    image: "assets/splash.png"

 

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/sound_effects/
    - assets/lotties/
    - assets/avatar/
    - assets/avatar/mouth/
    - assets/avatar/accessories/
    - assets/avatar/backgrounds/
    - assets/avatar/costumes/
    - assets/avatar/costumes/singularity/
    - assets/avatar/top/
    - assets/avatar/bottom/
    - assets/txt/
    - assets/onnx/
    - assets/voice_styles/

